function header(){
var html = "";
html += '<link href="https://fonts.googleapis.com/css?family=Charmonman:400,700|Noto+Serif+SC" rel="stylesheet">';
html += '<header style="border: 0.5px">';
html += '<h1><a id="logo" href="home.html">Ssavadeumuhl.com</a></h1>';
html += '<div id="navdiv">';
html += '<nav>';
html += '<div class="t2"align="center">';
html += '<ul class="ddmenu">';
html += '<li><a href="HOME.html">ホーム</a></li>';
html += '<li><a href="#">活動/記事</a><ul>';
html += '<li><a href="DTM.html">音楽活動 &raquo;</a><ul>';
html += '<li><a href="DTM1.html">DTM</a></li>';
html += '<li><a href="DTM2.html">serum</a></li>';
html += '<li><a href="DTM3.html">vital</a></li>';
html += '<li><a href="DTM4.html">zebra2</a></li>';
html += '<li><a href="DTM5.html">その他</a></li>';
html += '</ul></li>';
html += '<li><a href="CG.html">CG &raquo;</a><ul>';
html += '<li><a href="CG1.html">houdini</a></li>';
html += '<li><a href="CG2.html">blender</a></li>';
html += '<li><a href="CG3.html">その他</a></li>';
html += '</ul></li>';
html += '<li><a href="web.html">ウェブ &raquo;</a><ul>';
html += '<li><a href="WEBK.html">記事</a></li>';
html += '<li><a href="WEB_sample.html">サンプル</a></li>';
html += '<li><a href="WEB_other.html">その他</a></li>';
html += '</ul></li>';
html += '<li><a href="game.html">ゲーム&raquo;</a><ul>';
html += '<li><a href="game1.html">記事</a></li>';
html += '<li><a href="game2.html">ゲーム一覧</a></li>';
html += '</ul></li>';
html += '<li><a href="VST.html">vstプラグイン&raquo;</a><ul>';
html += '<li><a href="VST1.html">楽器</a></li>';
html += '<li><a href="VST2.html">エフェクト</a></li>';
html += '</ul></li>';
html += '<li><a href="artwork.html">アートワーク</a></li>';
html += '</ul></li>';
html += '</header>';
html += '</div></nav>';
document.write(html);
}
